package:
  name: jana2
  version: "2.2.1.rc1.p3"  # JANA 2.2.1.rc1, p3 - packaging version 3

source:
  url: https://github.com/JeffersonLab/JANA2/archive/refs/tags/v2.2.1-rc1.tar.gz  # adjust the version tag
  sha256: 7b65ce967d9c0690e22f4450733ead4acebf8fa510f792e0e4a6def14fb739b1  # you need to calculate this for the tar.gz file

build:
  #number: 0
  #skip: True  # [not win] If you do not support Windows
  skip: True  # [win or osx]

requirements:
  build:
    - cmake
    - python
    - make  # [unix]
    - {{ compiler('cxx') }}
  host:
    - {{ compiler('cxx') }}
  run:
    - root
    - python


test:
  commands:
    - command -v jana  # replace 'jana' with an actual binary name if different

about:
  home: https://github.com/JeffersonLab/JANA2
  license: MIT  # specify the correct license
  license_file: LICENSE
  summary: "Modular reconstruction framework for NP and HEP experiments"
  description: |
    JANA is a C++ framework for multi-threaded HENP (High Energy and Nuclear Physics) event reconstruction. 
    It is very efficient at multi-threading with a design that makes it easy for less experienced programmers 
    to contribute pieces to the larger reconstruction project. The same JANA program can be used to easily do 
    partial or full reconstruction, fully maximizing the available cores for the current job.
  documentation: https://jeffersonlab.github.io/JANA2/

extra:
  recipe-maintainers:
    - DraTeots  # add conda-forge maintainers later
